//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCapstoneGCCarDealership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string carID { get; set; }
        public string carMake { get; set; }
        public string carModel { get; set; }
        public string carYear { get; set; }
        public string carColor { get; set; }
    }
}
